/**
 * Bundled Australian legal-term dictionary (research §7, "Terms KB").
 *
 * Australia has no equivalent of the Korean 법령용어 API, so the reference
 * server's terminology tools have no upstream to call. This table is the
 * substitute, and its rules follow from that:
 *
 *  - **`plain` and `legal` are descriptions, never quoted definitions.** No
 *    statutory text is reproduced or paraphrased as if it were the
 *    provision's own words. Where a term genuinely has a statutory meaning,
 *    the entry carries a *pointer* — `provisions` — and the caller fetches
 *    the real text with `get_term_provisions(includeText: true)` or
 *    `get_law_text`. That keeps a summary from hardening into a citation.
 *  - **`titleId` is only ever a Federal Register id already verified in
 *    `law-alias-data.ts`,** which is why it is looked up from that table
 *    rather than retyped. State and territory Acts are not on the Federal
 *    Register, so their entries carry a title and a pinpoint and no id: the
 *    text tools will decline to fetch rather than guess.
 *  - **A miss in this table is a miss in this table.** It is not evidence
 *    that a term is not a legal term; the KB tools say so in as many words.
 *
 * Pinpoints are the anchors practitioners cite. They can move when an Act is
 * amended, so every tool that prints one also prints the way to read the
 * current text.
 */

import { LAW_ALIAS_ENTRIES } from "./law-alias-data.js"

/** A statutory anchor for a term: where the meaning or the standard lives. */
export interface TermProvision {
  /** Full title as it should be cited, including the jurisdiction bracket. */
  title: string
  /** Federal Register id, present only for Commonwealth titles already verified. */
  titleId?: string
  /** Provision reference in the `section-ref` grammar: `s 18`, `sch 2 s 18`, `pt 2-3`. */
  ref: string
}

export interface LegalTermEntry {
  /** Canonical legal term, lower case unless it is a proper name. */
  term: string
  /** Plain-English meaning — what a non-lawyer needs to understand it. */
  plain: string
  /** How the term functions in law: elements, the test, the usual dispute. */
  legal?: string
  /** Statutory anchors, most-central first. */
  provisions?: TermProvision[]
  /** Related terms in this table. */
  seeAlso?: string[]
  /** Everyday phrasings that should resolve to this term ("sacked", "ripped off"). */
  plainAliases?: string[]
}

function idFor(alias: string): string | undefined {
  return LAW_ALIAS_ENTRIES.find((entry) => entry.alias === alias)?.titleId
}

/** Builder for a Commonwealth title whose register id is in the alias table. */
function act(alias: string, title: string): (ref: string) => TermProvision {
  const titleId = idFor(alias)
  return (ref) => ({ title, ...(titleId ? { titleId } : {}), ref })
}

/** Builder for a title with no verified register id (state, territory, unlisted). */
function untracked(title: string): (ref: string) => TermProvision {
  return (ref) => ({ title, ref })
}

const cca = act("CCA", "Competition and Consumer Act 2010 (Cth)")
/** The ACL is CCA schedule 2 — the schedule must stay in the ref (s 18 ≠ sch 2 s 18). */
const acl = (ref: string): TermProvision => {
  const built = cca(`sch 2 ${ref}`)
  return { ...built, title: "Competition and Consumer Act 2010 (Cth) sch 2 (Australian Consumer Law)" }
}
const fw = act("FW Act", "Fair Work Act 2009 (Cth)")
const whs = act("WHS Act", "Work Health and Safety Act 2011 (Cth)")
const corps = act("Corps Act", "Corporations Act 2001 (Cth)")
const ppsa = act("PPSA", "Personal Property Securities Act 2009 (Cth)")
const itaa97 = act("ITAA 1997", "Income Tax Assessment Act 1997 (Cth)")
const itaa36 = act("ITAA 1936", "Income Tax Assessment Act 1936 (Cth)")
const gst = act("GST Act", "A New Tax System (Goods and Services Tax) Act 1999 (Cth)")
const taa = act("TAA", "Taxation Administration Act 1953 (Cth)")
const fbt = act("FBTAA", "Fringe Benefits Tax Assessment Act 1986 (Cth)")
const privacy = act("Privacy Act", "Privacy Act 1988 (Cth)")
const foi = act("FOI Act", "Freedom of Information Act 1982 (Cth)")
const evidence = act("Evidence Act (Cth)", "Evidence Act 1995 (Cth)")
const crimesCth = act("Crimes Act (Cth)", "Crimes Act 1914 (Cth)")
const aia = act("AIA", "Acts Interpretation Act 1901 (Cth)")
const legAct = act("LA 2003", "Legislation Act 2003 (Cth)")
const judiciary = act("Judiciary Act", "Judiciary Act 1903 (Cth)")
const adjr = act("ADJR Act", "Administrative Decisions (Judicial Review) Act 1977 (Cth)")
const constitution = act("Constitution", "Australian Constitution")
const migration = act("Migration Act", "Migration Act 1958 (Cth)")
const nta = act("NTA", "Native Title Act 1993 (Cth)")
const epbc = act("EPBC Act", "Environment Protection and Biodiversity Conservation Act 1999 (Cth)")
const slavery = act("Modern Slavery Act", "Modern Slavery Act 2018 (Cth)")

/**
 * The Criminal Code is the *unnumbered* Schedule to the Criminal Code Act
 * 1995 (Cth) — FRL labels it "Schedule—The Criminal Code", so a numbered
 * schedule pinpoint never matches its table of contents. The id is therefore
 * withheld on purpose: the pinpoint is right for a human, and the text tools
 * decline rather than fail confusingly.
 */
const code = untracked("Criminal Code Act 1995 (Cth) sch (the Criminal Code)")
const ucpr = untracked("Uniform Civil Procedure Rules 2005 (NSW)")
const cpaNsw = untracked("Civil Procedure Act 2005 (NSW)")
const claNsw = untracked("Civil Liability Act 2002 (NSW)")
const defamation = untracked("Defamation Act 2005 (NSW)")
const rpaNsw = untracked("Real Property Act 1900 (NSW)")
const conveyancing = untracked("Conveyancing Act 1919 (NSW)")
const sentencing = untracked("Crimes (Sentencing Procedure) Act 1999 (NSW)")
const criminalProcedure = untracked("Criminal Procedure Act 1986 (NSW)")
const bailNsw = untracked("Bail Act 2013 (NSW)")
const limitation = untracked("Limitation Act 1969 (NSW)")
const restraints = untracked("Restraints of Trade Act 1976 (NSW)")
const fcaAct = untracked("Federal Court of Australia Act 1976 (Cth)")
const scaNsw = untracked("Supreme Court Act 1970 (NSW)")

export const LEGAL_TERM_ENTRIES: readonly LegalTermEntry[] = [
  // ── Consumer law (Australian Consumer Law = CCA sch 2) ──────────────────
  { term: "consumer", plain: "A person or business that buys goods or services and gets the protection of the Australian Consumer Law.", legal: "ACL s 3 sets the test: goods or services acquired for personal, domestic or household use, or under a monetary threshold set by that section (the figure has been raised over time). Buying to re-supply or to use up in production takes you outside it.", provisions: [acl("s 3")], seeAlso: ["consumer guarantee", "acceptable quality"], plainAliases: ["customer", "shopper", "buyer"] },
  { term: "misleading or deceptive conduct", plain: "Doing or saying something in business that leads people into error — even honestly and without meaning to.", legal: "ACL s 18 is the central consumer/commercial prohibition. No intention is required and no defence of honesty exists; representations about the future are dealt with separately by s 4. Note the trap: CCA s 18 is about Commission meetings — the conduct provision is sch 2 s 18.", provisions: [acl("s 18"), acl("s 4")], seeAlso: ["false or misleading representations", "unconscionable conduct"], plainAliases: ["ripped off", "misled", "false advertising", "lied to me"] },
  { term: "false or misleading representations", plain: "Specific false claims about goods or services — fake discounts, invented endorsements, wrong country of origin.", legal: "ACL s 29 lists the prohibited representations. Unlike s 18 these attract civil pecuniary penalties and criminal liability under the mirror offence provisions.", provisions: [acl("s 29"), acl("s 151")], seeAlso: ["misleading or deceptive conduct", "pecuniary penalty"] },
  { term: "unconscionable conduct", plain: "Taking advantage of someone who cannot really protect their own interests, in a way the law treats as beyond hard bargaining.", legal: "ACL pt 2-2: s 20 preserves the unwritten-law doctrine, s 21 is the statutory prohibition in connection with goods or services, s 22 lists the factors a court may consider. Applies to small-business dealings, not just consumers.", provisions: [acl("pt 2-2"), acl("s 21"), acl("s 22")], seeAlso: ["unfair contract term", "misleading or deceptive conduct"], plainAliases: ["took advantage of me", "bullied into signing"] },
  { term: "unfair contract term", plain: "A term in a take-it-or-leave-it contract that tips the balance too far towards the party that wrote it.", legal: "ACL pt 2-3 (ss 23-28). A term is unfair under s 24 if it causes significant imbalance, is not reasonably necessary to protect legitimate interests, and would cause detriment. s 25 gives examples; s 27 presumes a contract is standard form unless proved otherwise. Since 2023 unfair terms attract penalties, not just voidness.", provisions: [acl("pt 2-3"), acl("s 24"), acl("s 25"), acl("s 27")], seeAlso: ["standard form contract", "unconscionable conduct"], plainAliases: ["unfair clause", "one-sided contract", "fine print"] },
  { term: "standard form contract", plain: "A contract handed over pre-written, with no real chance to negotiate the wording.", legal: "ACL s 27 presumes standard form and lists what a court weighs — bargaining power, whether the term was prepared before discussion, whether the other party could only accept or reject.", provisions: [acl("s 27")], seeAlso: ["unfair contract term"] },
  { term: "consumer guarantee", plain: "Automatic rights that come with almost everything you buy — the seller cannot contract out of them.", legal: "ACL pt 3-2 div 1 (ss 51-59 goods, ss 60-63 services). They are statutory guarantees, not contractual warranties, so a warranty document narrower than the guarantees does not displace them.", provisions: [acl("pt 3-2"), acl("s 54"), acl("s 60"), acl("s 64")], seeAlso: ["acceptable quality", "major failure", "guarantee exclusion"], plainAliases: ["warranty", "refund rights", "my rights when something breaks"] },
  { term: "acceptable quality", plain: "Goods must be safe, durable, free from defects, acceptable in appearance and do what such goods normally do.", legal: "ACL s 54, judged by what a reasonable consumer fully acquainted with the state of the goods would regard as acceptable, taking price and any disclosure into account.", provisions: [acl("s 54")], seeAlso: ["consumer guarantee", "major failure"] },
  { term: "major failure", plain: "A fault so serious you can choose a refund or replacement instead of accepting a repair.", legal: "ACL s 260 for goods and s 268 for services. Below that threshold the supplier gets to choose the remedy, which is why the classification is usually the fight.", provisions: [acl("s 260"), acl("s 268")], seeAlso: ["consumer guarantee", "acceptable quality"], plainAliases: ["want a refund not a repair"] },
  { term: "guarantee exclusion", plain: "A clause saying the consumer guarantees do not apply — generally void.", legal: "ACL s 64 makes any term excluding, restricting or modifying the guarantees void. s 64A allows limitation to resupply or refund for goods and services not ordinarily acquired for personal, domestic or household use, and only if reliance is fair and reasonable.", provisions: [acl("s 64"), acl("s 64A")], seeAlso: ["consumer guarantee", "unfair contract term"] },
  { term: "cooling-off period", plain: "A short window after signing when you can pull out without giving a reason.", legal: "There is no general cooling-off right in Australian law. It exists where a statute creates it: ACL s 82 for unsolicited consumer agreements, and separate state regimes for residential property, credit and some insurance. Check the specific regime before advising there is one.", provisions: [acl("s 82")], seeAlso: ["unsolicited consumer agreement"], plainAliases: ["change my mind", "cancel after signing", "get out of the contract"] },
  { term: "unsolicited consumer agreement", plain: "A sale made after an uninvited approach — door-to-door, cold call, street stall.", legal: "ACL pt 3-2 div 2 (ss 69-95): negotiation and disclosure rules, the s 82 termination right, and restrictions on supplying or taking payment during the termination period.", provisions: [acl("pt 3-2"), acl("s 82")], seeAlso: ["cooling-off period"], plainAliases: ["door to door", "cold call sale"] },
  { term: "single price", plain: "Advertised prices must show the total you actually pay, including GST.", legal: "ACL s 48: a supplier must specify the single total price in a prominent way when a component of the price is stated. A 'plus GST' headline to consumers is the classic breach.", provisions: [acl("s 48")], seeAlso: ["taxable supply", "false or misleading representations"] },
  { term: "bait advertising", plain: "Advertising a bargain you never had enough of, to pull people in.", legal: "ACL s 35: advertising goods or services at a specified price without reasonable grounds to believe they can be supplied in reasonable quantities for a reasonable period.", provisions: [acl("s 35")], seeAlso: ["false or misleading representations"] },
  { term: "product recall", plain: "Pulling an unsafe product back off the market.", legal: "ACL pt 3-3: suppliers must notify voluntary recalls, and the responsible Minister may order a compulsory recall under s 122.", provisions: [acl("pt 3-3"), acl("s 122")], seeAlso: ["consumer guarantee"] },
  { term: "pecuniary penalty", plain: "A civil fine a court orders a business to pay for breaking the rules.", legal: "ACL s 224 for consumer-law contraventions; the maximum for a body corporate is set by a formula (greatest of a fixed sum, three times the benefit, or a share of turnover) that has been increased repeatedly — read the current text before quoting a figure.", provisions: [acl("s 224")], seeAlso: ["false or misleading representations"] },
  { term: "class action", plain: "One proceeding run on behalf of a group of people with the same complaint.", legal: "Federal Court of Australia Act 1976 (Cth) pt IVA is the representative-proceeding regime; Civil Procedure Act 2005 (NSW) pt 10 and the Victorian equivalent mirror it. Seven or more claimants with claims arising from the same or similar circumstances.", provisions: [fcaAct("pt IVA"), cpaNsw("pt 10")], seeAlso: ["misleading or deceptive conduct"], plainAliases: ["group claim", "join a lawsuit"] },

  // ── Employment and workplace safety ────────────────────────────────────
  { term: "unfair dismissal", plain: "Being sacked in a way that was harsh, unjust or unreasonable.", legal: "FW Act s 385 sets the four limbs (dismissed; harsh/unjust/unreasonable; not consistent with the Small Business Fair Dismissal Code; not a genuine redundancy). s 387 lists the criteria, s 382 the eligibility gate, and s 394 the 21-day filing limit that ends most claims before they start.", provisions: [fw("s 385"), fw("s 387"), fw("s 382"), fw("s 394")], seeAlso: ["genuine redundancy", "constructive dismissal", "minimum employment period"], plainAliases: ["sacked", "fired", "let go", "lost my job unfairly"] },
  { term: "genuine redundancy", plain: "The job itself is no longer needed, so the dismissal is not unfair.", legal: "FW Act s 389: the employer no longer requires the job to be done by anyone because of operational changes, consultation obligations in any applicable award or agreement were met, and redeployment within the employer or an associated entity was not reasonable.", provisions: [fw("s 389"), fw("s 119")], seeAlso: ["unfair dismissal", "redundancy pay"], plainAliases: ["made redundant", "position abolished"] },
  { term: "constructive dismissal", plain: "You resigned, but only because the employer's conduct left you no real choice.", legal: "FW Act s 386(1)(b) treats a resignation forced by conduct of the employer as a dismissal. The test is whether the employer engaged in conduct with the intent, or the probable result, of ending the employment.", provisions: [fw("s 386")], seeAlso: ["unfair dismissal", "adverse action"], plainAliases: ["forced to resign", "had to quit"] },
  { term: "adverse action", plain: "Punishing someone at work for exercising a right — sacking, demoting, cutting hours, refusing to hire.", legal: "FW Act pt 3-1. s 342 tabulates what counts as adverse action, s 341 defines workplace rights, s 340 prohibits the action, s 351 covers discrimination, and s 361 reverses the onus so the employer must prove the reason.", provisions: [fw("pt 3-1"), fw("s 342"), fw("s 340"), fw("s 361")], seeAlso: ["general protections", "workplace right"], plainAliases: ["punished for complaining", "demoted after I spoke up"] },
  { term: "general protections", plain: "The workplace rules that stop employers acting against you for using your rights, your union membership, or a protected attribute.", legal: "FW Act pt 3-1 (ss 334-378). Wider than unfair dismissal: it covers prospective employees and independent contractors, has no minimum service period, and uncapped compensation is available.", provisions: [fw("pt 3-1")], seeAlso: ["adverse action", "workplace right"] },
  { term: "workplace right", plain: "An entitlement, a role, or the ability to make a complaint about your job.", legal: "FW Act s 341: holding an entitlement or role under a workplace law or instrument, being able to start proceedings, or making a complaint or inquiry about employment.", provisions: [fw("s 341")], seeAlso: ["adverse action", "general protections"] },
  { term: "sham contracting", plain: "Calling a worker a contractor when they are really an employee, to avoid paying entitlements.", legal: "FW Act s 357 prohibits misrepresenting employment as an independent contracting arrangement; ss 358 and 359 cover dismissing or misleading a worker to convert them to a contractor.", provisions: [fw("s 357"), fw("s 358")], seeAlso: ["independent contractor", "unpaid internship"], plainAliases: ["ABN instead of a job", "fake contractor"] },
  { term: "independent contractor", plain: "Someone who runs their own business and is engaged for a result, rather than being employed.", legal: "FW Act s 15AA now directs attention to the real substance and practical reality of the relationship, not just the contract's labels — the definition was rewritten by the 2024 Closing Loopholes reforms, so read the current text before applying it.", provisions: [fw("s 15AA"), fw("s 12")], seeAlso: ["sham contracting", "casual employee"] },
  { term: "casual employee", plain: "An employee engaged without a firm advance commitment to ongoing work.", legal: "FW Act s 15A, substantially rewritten in 2024 to look at the real substance of the relationship and to add an employee-choice pathway to permanent work. The pre-2024 and post-2024 tests differ, so identify which version applied at the relevant time.", provisions: [fw("s 15A"), fw("s 66AAC")], seeAlso: ["independent contractor", "National Employment Standards"] },
  { term: "National Employment Standards", plain: "The minimum conditions every national-system employee gets, no matter what their contract says.", legal: "FW Act pt 2-2 (ss 59-131): maximum weekly hours, flexible work requests, parental, annual, personal/carer's, community service and long service leave, public holidays, notice of termination, redundancy pay, the Fair Work Information Statement and (from 2024) the right to disconnect.", provisions: [fw("pt 2-2"), fw("s 61")], seeAlso: ["modern award", "notice of termination"], plainAliases: ["minimum entitlements", "NES"] },
  { term: "modern award", plain: "An industry or occupation rulebook setting minimum pay and conditions above the NES.", legal: "FW Act pt 2-3. Awards cannot exclude the NES and are displaced (not removed) by an enterprise agreement, which must still pass the better off overall test.", provisions: [fw("pt 2-3"), fw("s 12")], seeAlso: ["enterprise agreement", "better off overall test"], plainAliases: ["award rates", "pay rates"] },
  { term: "enterprise agreement", plain: "A collective agreement between an employer and its employees, approved by the Fair Work Commission.", legal: "FW Act pt 2-4: bargaining in good faith, the approval requirements, and the nominal expiry date after which the agreement continues to operate until terminated or replaced.", provisions: [fw("pt 2-4"), fw("s 186")], seeAlso: ["better off overall test", "modern award"] },
  { term: "better off overall test", plain: "An enterprise agreement has to leave every employee better off than the award would.", legal: "FW Act s 193 (BOOT). Applied to each award-covered employee and each prospective employee, on a global rather than line-by-line basis since the 2023 amendments.", provisions: [fw("s 193")], seeAlso: ["enterprise agreement", "modern award"] },
  { term: "notice of termination", plain: "The warning period an employer must give before ending employment, or pay in lieu.", legal: "FW Act s 117: minimum notice scales with service, with an extra week for employees over 45 with at least two years' service. Contracts and awards can be more generous, never less.", provisions: [fw("s 117")], seeAlso: ["redundancy pay", "unfair dismissal"], plainAliases: ["notice period", "pay in lieu"] },
  { term: "redundancy pay", plain: "A severance payment scaled to how long you worked there.", legal: "FW Act s 119 sets the NES scale; s 121 excludes small business employers and employees with under 12 months' service; s 120 lets the Commission reduce the amount where other acceptable employment is obtained.", provisions: [fw("s 119"), fw("s 121")], seeAlso: ["genuine redundancy", "notice of termination"], plainAliases: ["severance", "payout"] },
  { term: "minimum employment period", plain: "How long you must have worked somewhere before you can claim unfair dismissal.", legal: "FW Act s 383: six months, or twelve months for a small business employer as defined in s 23. It does not gate a general protections claim.", provisions: [fw("s 383"), fw("s 23")], seeAlso: ["unfair dismissal", "general protections"] },
  { term: "accessorial liability", plain: "Managers, HR staff, advisers and related companies can be personally on the hook for an employer's breach.", legal: "FW Act s 550: a person 'involved in' a contravention is treated as having contravened it. Involvement requires actual knowledge of the essential facts.", provisions: [fw("s 550")], seeAlso: ["sham contracting"] },
  { term: "stop bullying order", plain: "An order from the Fair Work Commission telling repeated unreasonable behaviour at work to stop.", legal: "FW Act pt 6-4B: s 789FC allows a worker who is bullied at work to apply, provided there is a risk of continued bullying. The parallel stop sexual harassment jurisdiction sits in the same Part. It is preventative — it does not award compensation.", provisions: [fw("pt 6-4B"), fw("s 789FC")], seeAlso: ["adverse action"], plainAliases: ["bullied at work", "harassed at work"] },
  { term: "unpaid internship", plain: "Unpaid work experience — lawful only in narrow circumstances.", legal: "FW Act s 12 defines a vocational placement (required by an education course, and unpaid) which sits outside the definition of employee. Outside that, an unpaid arrangement that involves productive work for the business is usually an employment relationship attracting the full NES and award entitlements.", provisions: [fw("s 12")], seeAlso: ["sham contracting", "National Employment Standards"], plainAliases: ["work for free", "unpaid trial", "work experience"] },
  { term: "primary duty of care", plain: "A business must keep workers and others safe so far as is reasonably practicable.", legal: "WHS Act s 19 imposes the duty on a person conducting a business or undertaking; s 27 imposes a separate, non-delegable due-diligence duty on officers. The Commonwealth Act is the model law — NSW, Qld, SA, Tas, ACT and NT mirror it; Victoria retained its own Occupational Health and Safety Act 2004.", provisions: [whs("s 19"), whs("s 27"), whs("s 18")], seeAlso: ["reasonably practicable", "officer"], plainAliases: ["workplace safety", "duty to keep workers safe"] },
  { term: "reasonably practicable", plain: "What could sensibly be done about a risk, weighing how likely and how serious the harm is against the cost of fixing it.", legal: "WHS Act s 18 defines it for the safety duties: likelihood, degree of harm, knowledge of the risk and ways to eliminate it, availability and suitability of controls, and cost — cost being relevant only if grossly disproportionate.", provisions: [whs("s 18")], seeAlso: ["primary duty of care"] },

  // ── Corporations and insolvency ────────────────────────────────────────
  { term: "officer", plain: "Someone who really participates in running a company — not only the people with 'director' on the card.", legal: "Corporations Act s 9 definition of 'officer of a corporation': directors and secretaries, plus anyone who makes or participates in making decisions affecting a substantial part of the business, or who can significantly affect its financial standing. Reaches senior managers and, in some cases, advisers.", provisions: [corps("s 9")], seeAlso: ["directors' duties", "primary duty of care"] },
  { term: "directors' duties", plain: "The core legal obligations of running a company: care, good faith, proper purpose, no misuse of position or information.", legal: "Corporations Act ss 180-183 are civil penalty provisions; s 184 is the criminal counterpart requiring recklessness or intentional dishonesty. General law fiduciary duties run alongside them and are not displaced.", provisions: [corps("s 180"), corps("s 181"), corps("s 182"), corps("s 183"), corps("s 184")], seeAlso: ["business judgment rule", "officer", "insolvent trading"], plainAliases: ["director responsibilities", "what directors must do"] },
  { term: "business judgment rule", plain: "A defence for directors who made a genuine, informed commercial decision that turned out badly.", legal: "Corporations Act s 180(2): the judgment must be made in good faith for a proper purpose, without a material personal interest, on an informed basis, and in a rational belief that it is in the company's best interests. It protects only the s 180(1) care-and-diligence duty.", provisions: [corps("s 180")], seeAlso: ["directors' duties"] },
  { term: "insolvent trading", plain: "Letting a company keep taking on debts when it cannot pay the ones it has.", legal: "Corporations Act s 588G: a director contravenes if the company incurs a debt while insolvent and there were reasonable grounds to suspect insolvency. Personal liability for the loss follows; s 588GA (safe harbour) and s 588H (defences) are the escape routes.", provisions: [corps("s 588G"), corps("s 588GA"), corps("s 95A")], seeAlso: ["safe harbour", "solvency", "directors' duties"], plainAliases: ["trading while broke", "company cannot pay debts"] },
  { term: "safe harbour", plain: "Directors are shielded from insolvent trading liability while they genuinely work on a better outcome than administration.", legal: "Corporations Act s 588GA: from when the director starts developing a course of action reasonably likely to lead to a better outcome, until it stops being so. Conditional on paying employee entitlements and lodging tax returns.", provisions: [corps("s 588GA")], seeAlso: ["insolvent trading", "voluntary administration"] },
  { term: "solvency", plain: "Being able to pay your debts as and when they fall due.", legal: "Corporations Act s 95A defines solvent and insolvent in cash-flow terms; the balance sheet is evidence, not the test.", provisions: [corps("s 95A")], seeAlso: ["insolvent trading", "statutory demand"] },
  { term: "statutory demand", plain: "A formal demand for a company debt that, if ignored, lets a court presume the company is insolvent.", legal: "Corporations Act s 459E for the demand (minimum statutory amount, 21 days); s 459F for the consequence of non-compliance; s 459G for the strict 21-day window to apply to set it aside, which courts have no power to extend.", provisions: [corps("s 459E"), corps("s 459G")], seeAlso: ["solvency", "winding up"], plainAliases: ["21 day demand", "creditor demand"] },
  { term: "voluntary administration", plain: "An outside administrator takes control of a struggling company to see if it can be saved.", legal: "Corporations Act pt 5.3A. A moratorium on claims runs during the administration, creditors decide the company's future at the second meeting, and a deed of company arrangement is one of the outcomes.", provisions: [corps("pt 5.3A")], seeAlso: ["deed of company arrangement", "winding up", "safe harbour"] },
  { term: "deed of company arrangement", plain: "A binding deal between an insolvent company and its creditors about how debts will be dealt with.", legal: "Corporations Act pt 5.3A (s 444A onwards). It binds all unsecured creditors including dissenters, but generally not secured creditors or owners of property who do not vote for it.", provisions: [corps("s 444A")], seeAlso: ["voluntary administration"], plainAliases: ["DOCA"] },
  { term: "winding up", plain: "Closing a company down and distributing what is left to creditors.", legal: "Corporations Act ch 5: pt 5.4 for winding up in insolvency (including the s 459C presumptions), pt 5.4A for the just-and-equitable and other grounds, pt 5.5 for members' and creditors' voluntary winding up.", provisions: [corps("pt 5.4"), corps("pt 5.5")], seeAlso: ["statutory demand", "voluntary administration"], plainAliases: ["liquidation", "closing the company"] },
  { term: "unfair preference", plain: "A payment that let one creditor do better than the others just before the company collapsed.", legal: "Corporations Act s 588FA defines the preference; s 588FE makes it voidable when it is an insolvent transaction within the relation-back period; s 588FG provides the good faith defence for the creditor.", provisions: [corps("s 588FA"), corps("s 588FE"), corps("s 588FG")], seeAlso: ["winding up", "insolvent trading"], plainAliases: ["liquidator clawback", "asked to pay money back"] },
  { term: "creditor-defeating disposition", plain: "Shifting company assets out for less than they are worth so creditors cannot reach them.", legal: "Corporations Act s 588FDB (inserted by the 2020 illegal phoenixing reforms) with the officer liability provisions in ss 588GAB and 588GAC. Voidable under s 588FE and separately enforceable by ASIC.", provisions: [corps("s 588FDB")], seeAlso: ["unfair preference", "directors' duties"], plainAliases: ["phoenix company", "phoenixing"] },
  { term: "related party transaction", plain: "A public company giving a financial benefit to a director or their associates needs shareholder approval.", legal: "Corporations Act ch 2E (s 208 onwards) for public companies and registered schemes, with exceptions in ss 210-216 including arm's length terms and reasonable remuneration.", provisions: [corps("s 208")], seeAlso: ["material personal interest", "directors' duties"] },
  { term: "material personal interest", plain: "A real, personal stake a director has in something the board is deciding.", legal: "Corporations Act s 191 requires disclosure to the other directors; s 195 stops a public company director voting on the matter unless an exception applies.", provisions: [corps("s 191"), corps("s 195")], seeAlso: ["directors' duties", "related party transaction"], plainAliases: ["conflict of interest"] },
  { term: "separate legal entity", plain: "A company is its own legal person: its debts are not automatically its owners' debts.", legal: "Corporations Act s 119 (registration creates the body corporate) and s 124 (legal capacity of an individual plus corporate powers). Piercing the veil is exceptional; the statutory routes — insolvent trading, accessorial liability, safe-harbour failure — do the work instead.", provisions: [corps("s 119"), corps("s 124")], seeAlso: ["insolvent trading", "directors' duties"], plainAliases: ["corporate veil", "am I personally liable"] },
  { term: "statutory assumptions", plain: "Outsiders dealing with a company can assume its internal rules were followed.", legal: "Corporations Act s 128 sets when the assumptions may be made (including against a person who has themselves been misled) and s 129 lists them — the codified successor to the indoor management rule.", provisions: [corps("s 128"), corps("s 129")], seeAlso: ["separate legal entity"], plainAliases: ["indoor management rule"] },
  { term: "corporate whistleblower", plain: "Someone who reports company misconduct and gets legal protection for doing it.", legal: "Corporations Act pt 9.4AAA (ss 1317AA-1317AJ): eligible whistleblowers, eligible recipients, protection of identity, and compensation for detriment. Public sector disclosures run through the Public Interest Disclosure Act 2013 (Cth) instead.", provisions: [corps("pt 9.4AAA")], seeAlso: ["adverse action"], plainAliases: ["dobbing in the company", "reporting fraud at work"] },
  { term: "retail client", plain: "A financial-services customer who gets the full consumer-protection package.", legal: "Corporations Act s 761G, with the tests turned on product type and monetary and asset thresholds set by the section and the regulations, and s 761GA for the sophisticated investor route. Everyone who is not a wholesale client is retail.", provisions: [corps("s 761G")], seeAlso: ["managed investment scheme"] },
  { term: "continuous disclosure", plain: "A listed company must tell the market price-sensitive information promptly.", legal: "Corporations Act s 674 (and s 674A, which added a fault element in 2021) working with ASX Listing Rule 3.1 and its carve-outs. Breach exposes the entity to penalties and shareholder class actions.", provisions: [corps("s 674"), corps("s 674A")], seeAlso: ["class action"] },
  { term: "managed investment scheme", plain: "A pooled investment run by someone else, where investors have no day-to-day control.", legal: "Corporations Act s 9 definition, with s 601ED requiring registration when there are more than 20 members or the scheme was promoted by a person in the business of scheme promotion.", provisions: [corps("s 9"), corps("s 601ED")], seeAlso: ["retail client"] },
  { term: "security interest", plain: "A lender's claim over property that lets it take the property if the debt is not paid.", legal: "PPSA s 12 defines a security interest in substance-over-form terms and deems certain leases and consignments to be one; s 21 governs perfection, usually by registration on the PPSR, and priority follows perfection.", provisions: [ppsa("s 12"), ppsa("s 21")], seeAlso: ["caveat"], plainAliases: ["PPSR", "charge over assets", "secured loan"] },

  // ── Tax ─────────────────────────────────────────────────────────────────
  { term: "CGT event", plain: "The moment that triggers a capital gain or loss — usually selling an asset.", legal: "ITAA 1997 s 102-20: you make a gain or loss only if a CGT event happens. Div 104 lists the events; A1 (s 104-10, disposal) is the common one and its timing is the contract date, not settlement.", provisions: [itaa97("s 102-20"), itaa97("s 104-10")], seeAlso: ["cost base", "capital gains tax discount", "main residence exemption"], plainAliases: ["capital gains", "selling an investment property", "CGT"] },
  { term: "cost base", plain: "What the asset cost you, for working out the gain — including some later expenses.", legal: "ITAA 1997 s 110-25 sets out the five elements: acquisition money, incidental costs, ownership costs, capital improvement costs and title-preservation costs. Some elements are excluded where they have been deducted.", provisions: [itaa97("s 110-25")], seeAlso: ["CGT event"] },
  { term: "capital gains tax discount", plain: "Individuals and trusts halve a capital gain on an asset held long enough.", legal: "ITAA 1997 div 115: the discount percentage and the 12-month ownership requirement in s 115-25, with modifications for foreign residents and superannuation funds.", provisions: [itaa97("div 115"), itaa97("s 115-25")], seeAlso: ["CGT event"], plainAliases: ["50% discount", "held for a year"] },
  { term: "main residence exemption", plain: "Your home is generally free of capital gains tax.", legal: "ITAA 1997 s 118-110 gives the basic exemption; s 118-145 is the absence rule; the exemption is denied to foreign residents at the time of the CGT event and reduced where the dwelling was income-producing.", provisions: [itaa97("s 118-110"), itaa97("s 118-145")], seeAlso: ["CGT event"], plainAliases: ["selling my home", "family home tax"] },
  { term: "general deduction", plain: "You can deduct what you spend to earn your income, but not private or capital spending.", legal: "ITAA 1997 s 8-1: positive limbs (incurred in gaining or producing assessable income, or necessarily incurred in carrying on a business) and negative limbs (capital, private or domestic, exempt-income related, or specifically denied).", provisions: [itaa97("s 8-1")], seeAlso: ["ordinary income", "capital allowance"], plainAliases: ["tax deduction", "what can I claim"] },
  { term: "ordinary income", plain: "Income according to ordinary concepts — wages, business takings, rent, interest.", legal: "ITAA 1997 s 6-5, with s 6-10 bringing in statutory income and s 6-15 excluding what is not income. Residents are taxed on worldwide ordinary income; foreign residents on Australian-sourced income.", provisions: [itaa97("s 6-5"), itaa97("s 6-10")], seeAlso: ["tax residency", "general deduction"] },
  { term: "trading stock", plain: "Goods a business holds to sell.", legal: "ITAA 1997 s 70-10 defines it; div 70 governs the opening and closing valuation adjustments that convert purchases into cost of sales.", provisions: [itaa97("s 70-10")], seeAlso: ["general deduction"] },
  { term: "capital allowance", plain: "Writing off the cost of business equipment over the years you use it.", legal: "ITAA 1997 div 40: s 40-30 defines a depreciating asset, s 40-25 gives the deduction for decline in value, and effective life determines the rate. Small business pooling sits in subdiv 328-D.", provisions: [itaa97("div 40"), itaa97("s 40-30")], seeAlso: ["general deduction", "small business entity"], plainAliases: ["depreciation", "write off equipment"] },
  { term: "small business entity", plain: "A business small enough to get simplified tax rules and concessions.", legal: "ITAA 1997 s 328-110: carrying on a business with aggregated turnover under the threshold, tested on the previous or the current year. Different concessions use different turnover thresholds, so check which one applies.", provisions: [itaa97("s 328-110")], seeAlso: ["small business CGT concessions", "capital allowance"] },
  { term: "small business CGT concessions", plain: "Four concessions that can reduce or defer capital gains tax when a small business sells an asset.", legal: "ITAA 1997 div 152: the basic conditions in subdiv 152-A (including the maximum net asset value test and the active asset test), then the 15-year exemption, 50% active asset reduction, retirement exemption and rollover.", provisions: [itaa97("div 152")], seeAlso: ["small business entity", "CGT event"] },
  { term: "tax residency", plain: "Whether Australia taxes your worldwide income or only what you earn here.", legal: "ITAA 1936 s 6(1) definition of 'resident': the ordinary concepts test plus the domicile, 183-day and superannuation tests. Residency is a question of fact assessed year by year, and a tax treaty can override the outcome.", provisions: [itaa36("s 6")], seeAlso: ["ordinary income"], plainAliases: ["am I a tax resident", "living overseas tax"] },
  { term: "Part IVA", plain: "The general anti-avoidance rule: schemes with a dominant tax-benefit purpose can be unwound.", legal: "ITAA 1936 pt IVA (ss 177A-177F): a scheme, a tax benefit, and the conclusion from the eight factors in s 177D that a dominant purpose was to obtain it. The Commissioner may then cancel the benefit.", provisions: [itaa36("pt IVA"), itaa36("s 177D")], seeAlso: ["private ruling"], plainAliases: ["tax avoidance", "anti-avoidance"] },
  { term: "Division 7A", plain: "Money taken out of a private company by an owner is treated as a taxable dividend unless it is properly documented.", legal: "ITAA 1936 pt III div 7A: payments, loans and forgiven debts to shareholders and associates become deemed unfranked dividends unless a complying loan agreement with the minimum interest rate and maximum term is in place before lodgment day.", provisions: [itaa36("div 7A")], seeAlso: ["Part IVA"], plainAliases: ["director loan", "taking money out of my company"] },
  { term: "input tax credit", plain: "GST a business paid on its purchases and can claim back.", legal: "GST Act s 11-20 gives the entitlement for a creditable acquisition, defined in s 11-5 (acquired for a creditable purpose, the supply to you was taxable, you provide consideration and you are registered). A tax invoice is required to claim, and the four-year limit applies.", provisions: [gst("s 11-20"), gst("s 11-5"), gst("s 29-70")], seeAlso: ["taxable supply", "tax invoice"], plainAliases: ["claim GST back", "GST credit"] },
  { term: "taxable supply", plain: "A sale that carries GST.", legal: "GST Act s 9-5: supply for consideration, in the course of an enterprise, connected with Australia, by a registered or required-to-be-registered entity — and not GST-free (div 38) or input taxed (div 40).", provisions: [gst("s 9-5"), gst("s 9-40")], seeAlso: ["input tax credit", "GST registration threshold"] },
  { term: "tax invoice", plain: "The document that lets the buyer claim the GST back.", legal: "GST Act s 29-70 sets the required contents and the 28-day rule for issuing on request. Without one held at the time of lodgment the credit is generally not claimable.", provisions: [gst("s 29-70")], seeAlso: ["input tax credit"] },
  { term: "GST registration threshold", plain: "The turnover level at which a business must register for GST.", legal: "GST Act s 23-5 requires registration when GST turnover meets the registration turnover threshold set by the regulations, with a lower entry point for taxi and ride-sourcing drivers. Read the current figure rather than quoting one from memory.", provisions: [gst("s 23-5")], seeAlso: ["taxable supply"], plainAliases: ["do I need to register for GST"] },
  { term: "PAYG withholding", plain: "Tax an employer takes out of wages and sends to the ATO.", legal: "TAA sch 1 pt 2-5 div 12: s 12-35 covers payments to employees, s 12-190 the no-ABN withholding rule, and div 16 the reporting and remittance obligations. Failure to withhold can deny the employer's deduction.", provisions: [taa("sch 1 div 12")], seeAlso: ["PAYG instalments", "director penalty notice"], plainAliases: ["tax taken out of my pay", "PAYG"] },
  { term: "PAYG instalments", plain: "Regular prepayments of income tax by businesses and investors.", legal: "TAA sch 1 div 45: the Commissioner enters an entity into the system, and instalments are worked out on the instalment rate or the notified amount, credited against the eventual assessment.", provisions: [taa("sch 1 div 45")], seeAlso: ["PAYG withholding"] },
  { term: "private ruling", plain: "A binding answer from the ATO about how the law applies to your specific situation.", legal: "TAA sch 1 div 359. Public rulings sit in div 358 and oral rulings in div 360. A ruling binds the Commissioner in your favour; you are not bound to follow it, and it can be objected against.", provisions: [taa("sch 1 div 359"), taa("sch 1 div 358")], seeAlso: ["taxation objection", "Part IVA"], plainAliases: ["ask the ATO", "ATO ruling"] },
  { term: "taxation objection", plain: "The formal way to dispute an ATO assessment or decision.", legal: "TAA pt IVC: lodge an objection within the period allowed, then either seek review in the Administrative Review Tribunal or appeal to the Federal Court. The taxpayer bears the burden of proving the assessment excessive.", provisions: [taa("pt IVC")], seeAlso: ["private ruling", "merits review"], plainAliases: ["dispute a tax bill", "object to an assessment"] },
  { term: "director penalty notice", plain: "A notice making a company director personally liable for the company's unpaid PAYG, GST or super.", legal: "TAA sch 1 div 269. A lockdown notice (where returns were not lodged on time) leaves only payment as a remedy; otherwise appointing an administrator or liquidator within the notice period can remit the penalty.", provisions: [taa("sch 1 div 269")], seeAlso: ["insolvent trading", "PAYG withholding"], plainAliases: ["DPN", "personally liable for company tax"] },
  { term: "fringe benefit", plain: "A non-cash perk given to an employee, taxed to the employer.", legal: "FBTAA s 136(1) definition of 'fringe benefit', with the type-specific rules (cars, expense payments, loans, entertainment) in the operative Parts and the exemptions in s 58 onwards. FBT runs on a 1 April to 31 March year.", provisions: [fbt("s 136")], seeAlso: ["PAYG withholding"], plainAliases: ["company car tax", "staff perks tax", "FBT"] },

  // ── Privacy and information ────────────────────────────────────────────
  { term: "personal information", plain: "Information about an identified individual, or one who can reasonably be identified from it.", legal: "Privacy Act s 6(1). The test is reasonable identifiability, so information can be personal in one context and not another; it does not have to be true or recorded in a material form.", provisions: [privacy("s 6")], seeAlso: ["sensitive information", "Australian Privacy Principles"], plainAliases: ["my data", "my details"] },
  { term: "sensitive information", plain: "The higher-risk categories: health, race, politics, religion, sexuality, biometrics, criminal record.", legal: "Privacy Act s 6(1). It is a subset of personal information with stricter collection rules — generally consent plus reasonable necessity under APP 3.", provisions: [privacy("s 6"), privacy("sch 1")], seeAlso: ["personal information", "consent"] },
  { term: "Australian Privacy Principles", plain: "The thirteen rules about collecting, using, storing and disclosing personal information.", legal: "Privacy Act sch 1 (APPs 1-13): open handling, anonymity, collection, unsolicited information, notification, use and disclosure, direct marketing, cross-border disclosure, government identifiers, quality, security, access and correction.", provisions: [privacy("sch 1")], seeAlso: ["APP entity", "eligible data breach"], plainAliases: ["privacy rules", "APPs"] },
  { term: "APP entity", plain: "The agencies and businesses the privacy rules actually bind.", legal: "Privacy Act s 6(1): agencies and organisations. s 6D exempts most small businesses with annual turnover at or below the statutory threshold, subject to carve-outs for health service providers and traders in personal information.", provisions: [privacy("s 6"), privacy("s 6D")], seeAlso: ["Australian Privacy Principles"] },
  { term: "eligible data breach", plain: "A leak serious enough that affected people and the regulator must be told.", legal: "Privacy Act pt IIIC: s 26WE defines an eligible data breach (unauthorised access, disclosure or loss likely to result in serious harm), s 26WH allows a 30-day assessment, and s 26WK requires notification to the Commissioner and affected individuals.", provisions: [privacy("pt IIIC"), privacy("s 26WE")], seeAlso: ["Australian Privacy Principles"], plainAliases: ["data breach", "hacked", "data leak"] },
  { term: "cross-border disclosure", plain: "Sending personal information overseas keeps you responsible for what happens to it.", legal: "Privacy Act sch 1 APP 8, working with s 16C, which makes the discloser accountable for the overseas recipient's acts unless an exception (such as a substantially similar law with enforcement mechanisms, or informed consent) applies.", provisions: [privacy("sch 1"), privacy("s 16C")], seeAlso: ["Australian Privacy Principles"], plainAliases: ["offshore data", "cloud storage overseas"] },
  { term: "consent", plain: "Agreement that is genuinely voluntary, informed, specific and current.", legal: "Privacy Act s 6(1) defines consent as express or implied. The regulator's guidance treats bundled, buried or forced consent as no consent at all, which is what most privacy-clause disputes turn on.", provisions: [privacy("s 6")], seeAlso: ["Australian Privacy Principles", "sensitive information"] },
  { term: "freedom of information request", plain: "Asking a Commonwealth agency for its documents.", legal: "FOI Act s 15 for the request and time limits, s 11A for the right of access, and pt IV for the exemptions. Refusals go to internal review, then the Information Commissioner, then the Administrative Review Tribunal.", provisions: [foi("s 15"), foi("s 11A")], seeAlso: ["exempt document", "merits review"], plainAliases: ["FOI", "get government documents"] },
  { term: "exempt document", plain: "A government document that does not have to be released.", legal: "FOI Act pt IV: unconditional exemptions (national security, Cabinet, legal professional privilege) in div 2, and conditional exemptions in div 3 which are released unless disclosure would be contrary to the public interest under s 11A(5).", provisions: [foi("pt IV")], seeAlso: ["freedom of information request"] },

  // ── Defamation and civil liability ─────────────────────────────────────
  { term: "serious harm", plain: "Defamation now requires proof the publication really did (or is likely to) hurt your reputation.", legal: "Defamation Act 2005 (NSW) s 10A, inserted by the 2020 model amendments and mirrored in the other uniform jurisdictions from 1 July 2021. It is an element of the cause of action, normally decided before trial, and corporations must show serious financial loss.", provisions: [defamation("s 10A")], seeAlso: ["concerns notice", "justification"], plainAliases: ["damaged my reputation", "defamed"] },
  { term: "concerns notice", plain: "A written complaint you must send before suing for defamation.", legal: "Defamation Act 2005 (NSW) s 12B makes a concerns notice a precondition to commencing proceedings; pt 3 div 1 governs offers to make amends, which are a defence if reasonable and refused.", provisions: [defamation("s 12B"), defamation("pt 3")], seeAlso: ["serious harm"], plainAliases: ["defamation letter", "before suing for defamation"] },
  { term: "justification", plain: "The truth defence: if what was published is substantially true, there is no defamation.", legal: "Defamation Act 2005 (NSW) s 25 (substantial truth of the imputations carried) with s 26 contextual truth, which allows a defendant to rely on other, more serious true imputations.", provisions: [defamation("s 25"), defamation("s 26")], seeAlso: ["serious harm", "honest opinion"], plainAliases: ["it was true"] },
  { term: "public interest defence", plain: "A defence for responsible journalism and other publications on matters of public concern.", legal: "Defamation Act 2005 (NSW) s 29A, added in 2021: the matter concerns an issue of public interest and the defendant reasonably believed publication was in the public interest, judged against the listed factors.", provisions: [defamation("s 29A")], seeAlso: ["justification", "honest opinion"] },
  { term: "honest opinion", plain: "Genuine comment, clearly opinion rather than fact, on a matter of public interest.", legal: "Defamation Act 2005 (NSW) s 31: the matter must be opinion rather than a statement of fact, relate to a matter of public interest, and be based on proper material.", provisions: [defamation("s 31")], seeAlso: ["justification", "public interest defence"], plainAliases: ["just my opinion"] },
  { term: "duty of care", plain: "A legal responsibility to take reasonable care not to hurt someone.", legal: "In personal injury the statutory reformulation applies: Civil Liability Act 2002 (NSW) s 5B (foreseeability, not insignificant risk, and what a reasonable person would do) and s 5D (factual causation and scope of liability). Each state has an equivalent Act with different numbering — Victoria's is the Wrongs Act 1958.", provisions: [claNsw("s 5B"), claNsw("s 5D")], seeAlso: ["contributory negligence", "obvious risk"], plainAliases: ["negligence", "someone hurt me", "was it their fault"] },
  { term: "contributory negligence", plain: "Your damages are cut back if you helped cause your own injury.", legal: "Civil Liability Act 2002 (NSW) s 5R applies the same standard of care to the plaintiff; s 5S permits a reduction of 100% where the court thinks it just. Intoxication and failure to wear a seatbelt carry statutory presumptions.", provisions: [claNsw("s 5R"), claNsw("s 5S")], seeAlso: ["duty of care"], plainAliases: ["partly my fault"] },
  { term: "obvious risk", plain: "You are presumed to have known about risks that would be obvious to a reasonable person.", legal: "Civil Liability Act 2002 (NSW) ss 5F-5H (definition, presumption of awareness, no proactive duty to warn) and s 5L, which bars liability for harm from the materialisation of an obvious risk of a dangerous recreational activity.", provisions: [claNsw("s 5F"), claNsw("s 5L")], seeAlso: ["duty of care", "contributory negligence"] },
  { term: "limitation period", plain: "The deadline for starting a court case — miss it and the claim is usually dead.", legal: "Limitation Act 1969 (NSW) s 14 gives six years for contract and most torts; personal injury runs on the three-year discoverability rule in s 50C; defamation is one year under s 14B; child abuse claims have no limitation period. Each state has its own Act, and extensions are discretionary and narrow.", provisions: [limitation("s 14"), limitation("s 50C"), limitation("s 14B")], seeAlso: ["duty of care", "serious harm"], plainAliases: ["too late to sue", "deadline to sue", "how long do I have"] },

  // ── Property ────────────────────────────────────────────────────────────
  { term: "Torrens title", plain: "Government-guaranteed land ownership: what the register says is what you own.", legal: "Real Property Act 1900 (NSW) and its state counterparts. The register is the source of title rather than evidence of it, so the historical chain of deeds does not have to be traced.", provisions: [rpaNsw("s 42")], seeAlso: ["indefeasibility", "caveat"], plainAliases: ["land title", "certificate of title"] },
  { term: "indefeasibility", plain: "Once you are registered as owner, earlier defects in the paperwork generally cannot unseat you.", legal: "Real Property Act 1900 (NSW) s 42 makes the registered proprietor's title paramount subject to the listed exceptions, of which fraud by or known to the registered proprietor is the principal one. Personal equities can still be enforced against the proprietor.", provisions: [rpaNsw("s 42")], seeAlso: ["Torrens title", "caveat"] },
  { term: "caveat", plain: "A warning lodged on a land title that stops dealings until your claim is sorted out.", legal: "Real Property Act 1900 (NSW) s 74F requires a caveatable interest — a legal or equitable estate in the land, not merely a debt. s 74K allows the Supreme Court to extend it and s 74P imposes compensation for a caveat lodged without reasonable cause.", provisions: [rpaNsw("s 74F"), rpaNsw("s 74P")], seeAlso: ["indefeasibility", "security interest"], plainAliases: ["freeze the title", "stop the sale of a property"] },
  { term: "easement", plain: "A right to use part of someone else's land — a driveway, a drainage line, a right of way.", legal: "Conveyancing Act 1919 (NSW) s 88 sets out what an instrument creating an easement must identify for it to be enforceable; s 88K lets a court impose an easement reasonably necessary for the effective use of other land, on compensation.", provisions: [conveyancing("s 88"), conveyancing("s 88K")], seeAlso: ["restrictive covenant", "Torrens title"], plainAliases: ["right of way", "driveway rights", "shared driveway"] },
  { term: "restrictive covenant", plain: "A promise attached to land limiting what can be built or done on it.", legal: "Conveyancing Act 1919 (NSW) s 88 governs enforceability against successors; s 89 allows the Supreme Court to modify or extinguish a covenant that is obsolete or impedes reasonable user.", provisions: [conveyancing("s 88"), conveyancing("s 89")], seeAlso: ["easement"], plainAliases: ["building restriction on my block"] },
  { term: "joint tenancy", plain: "Co-ownership with survivorship: when one owner dies their share passes automatically to the others.", legal: "Contrasted with tenancy in common, where each owner has a distinct (possibly unequal) share that passes under their will. Conveyancing Act 1919 (NSW) s 26 presumes a tenancy in common for a conveyance to two or more persons unless a joint tenancy is expressed.", provisions: [conveyancing("s 26")], seeAlso: ["Torrens title"], plainAliases: ["joint names", "who gets the house if one owner dies"] },

  // ── Criminal law and evidence ──────────────────────────────────────────
  { term: "mens rea", plain: "The guilty mind: the state of mind the prosecution has to prove alongside the act.", legal: "For Commonwealth offences the common law language is replaced by the fault elements in the Criminal Code ch 2 — intention (s 5.2), knowledge (s 5.3), recklessness (s 5.4) and negligence (s 5.5), with s 5.6 supplying the default where the offence is silent. The Code is the unnumbered Schedule to the Criminal Code Act 1995 (Cth), so a numbered-schedule pinpoint will not resolve.", provisions: [code("s 5.1"), code("s 5.6")], seeAlso: ["actus reus", "beyond reasonable doubt"], plainAliases: ["guilty mind", "did they mean to do it"] },
  { term: "actus reus", plain: "The physical part of an offence: the conduct, the circumstances and the result.", legal: "Criminal Code ch 2 s 4.1 sets out the physical elements — conduct, a circumstance in which conduct occurs, or a result of conduct — and s 4.2 requires that conduct be voluntary.", provisions: [code("s 4.1"), code("s 4.2")], seeAlso: ["mens rea"], plainAliases: ["the act itself"] },
  { term: "beyond reasonable doubt", plain: "The criminal standard: the jury must be sure.", legal: "Evidence Act 1995 (Cth) s 141 states the standard for the prosecution case and the balance of probabilities for matters the defendant must prove. Judges are discouraged from elaborating on the phrase for a jury.", provisions: [evidence("s 141"), evidence("s 140")], seeAlso: ["balance of probabilities", "mens rea"], plainAliases: ["how sure does a jury need to be"] },
  { term: "balance of probabilities", plain: "The civil standard: more likely than not.", legal: "Evidence Act 1995 (Cth) s 140, which requires the court to consider the nature of the cause of action, the subject matter and the gravity of the alleged facts — the statutory form of the Briginshaw principle.", provisions: [evidence("s 140")], seeAlso: ["beyond reasonable doubt"], plainAliases: ["more likely than not", "51 percent"] },
  { term: "summary offence", plain: "A less serious charge decided by a magistrate without a jury.", legal: "Crimes Act 1914 (Cth) s 4H defines summary offences and s 4G indictable offences (punishable by imprisonment exceeding 12 months); ss 4J and 4JA allow some indictable offences to be dealt with summarily with consent. State classifications use their own tables.", provisions: [crimesCth("s 4H"), crimesCth("s 4G")], seeAlso: ["indictable offence", "committal"], plainAliases: ["local court charge", "minor charge"] },
  { term: "indictable offence", plain: "A serious charge that can go to a judge and jury.", legal: "Crimes Act 1914 (Cth) s 4G. In practice many indictable matters are dealt with summarily under ss 4J-4JA; the classification also drives committal, time limits and the available penalties.", provisions: [crimesCth("s 4G")], seeAlso: ["summary offence", "committal"], plainAliases: ["serious charge", "jury trial"] },
  { term: "committal", plain: "The Local Court stage that decides whether a serious charge goes up to a higher court.", legal: "Criminal Procedure Act 1986 (NSW) ch 3 pt 2, reshaped by the 2018 reforms: the magistrate's role is now largely case management and charge certification rather than testing whether there is a prima facie case.", provisions: [criminalProcedure("ch 3")], seeAlso: ["indictable offence"], plainAliases: ["going up to the District Court"] },
  { term: "bail", plain: "Being released while your case is on foot, sometimes with conditions.", legal: "Bail Act 2013 (NSW): the unacceptable risk test in s 19 (failure to appear, further offences, endangering safety, interference with witnesses), the show cause requirement for listed offences in s 16A, and s 20A limiting repeat applications.", provisions: [bailNsw("s 19"), bailNsw("s 16A")], seeAlso: ["parole"], plainAliases: ["get out of custody", "bail conditions"] },
  { term: "parole", plain: "Serving the rest of a prison sentence in the community under supervision.", legal: "Set up at sentence: Crimes (Sentencing Procedure) Act 1999 (NSW) s 44 requires the court to set a non-parole period and a balance of term, with reasons required if the balance exceeds one third. Release and revocation are then administered under the Crimes (Administration of Sentences) Act 1999 (NSW).", provisions: [sentencing("s 44")], seeAlso: ["probation", "bail"], plainAliases: ["early release", "out on parole"] },
  { term: "probation", plain: "A community-based order instead of prison — supervision and conditions rather than custody.", legal: "Not a current NSW term: the 2018 sentencing reforms replaced good behaviour bonds and similar orders with community correction orders, conditional release orders and intensive correction orders under the Crimes (Sentencing Procedure) Act 1999 (NSW). Other states retain their own labels, so name the jurisdiction before advising.", seeAlso: ["parole"], plainAliases: ["community service", "good behaviour bond"] },
  { term: "hearsay", plain: "Repeating what someone else said, to prove what they said was true.", legal: "Evidence Act 1995 (Cth) s 59 states the rule (a previous representation is not admissible to prove an asserted fact), with the wide exceptions in ss 60-75 including first-hand hearsay where the maker is unavailable. Queensland, WA and SA are not uniform evidence jurisdictions.", provisions: [evidence("s 59")], seeAlso: ["improperly obtained evidence"], plainAliases: ["he said she said", "second hand evidence"] },
  { term: "client legal privilege", plain: "You can refuse to hand over confidential lawyer-client communications.", legal: "Evidence Act 1995 (Cth) s 118 (advice privilege) and s 119 (litigation privilege), with loss of privilege in ss 122-126. Outside court proceedings the common law doctrine of legal professional privilege applies on similar lines.", provisions: [evidence("s 118"), evidence("s 119")], seeAlso: ["without prejudice"], plainAliases: ["legal professional privilege", "lawyer confidentiality"] },
  { term: "without prejudice", plain: "Settlement talks generally cannot be waved in front of a court later.", legal: "Evidence Act 1995 (Cth) s 131 excludes evidence of communications and documents made in connection with an attempt to settle a dispute, subject to the exceptions in s 131(2). Writing 'without prejudice' on a letter that is not a genuine settlement attempt does not create the protection.", provisions: [evidence("s 131")], seeAlso: ["client legal privilege", "concerns notice"], plainAliases: ["settlement offer letter", "off the record"] },
  { term: "improperly obtained evidence", plain: "Evidence gathered unlawfully can be thrown out — but it is a balancing exercise, not automatic.", legal: "Evidence Act 1995 (Cth) s 138: evidence obtained improperly or in contravention of an Australian law is not to be admitted unless the desirability of admitting it outweighs the undesirability, weighed against the s 138(3) factors.", provisions: [evidence("s 138")], seeAlso: ["hearsay"], plainAliases: ["illegal search", "police did the wrong thing"] },
  { term: "privilege against self-incrimination", plain: "You do not have to answer a question if the answer could expose you to a penalty.", legal: "Evidence Act 1995 (Cth) s 128 lets a witness object and, if the court certifies, gives use and derivative-use immunity for the compelled answer. Many regulatory statutes abrogate the privilege and substitute an immunity.", provisions: [evidence("s 128")], seeAlso: ["client legal privilege"], plainAliases: ["right to silence", "plead the fifth"] },
  { term: "tendency and coincidence evidence", plain: "Evidence about someone's past behaviour, used to suggest they acted the same way again.", legal: "Evidence Act 1995 (Cth) s 97 (tendency) and s 98 (coincidence) require reasonable notice and significant probative value; s 101 adds a further threshold in criminal proceedings against the defendant.", provisions: [evidence("s 97"), evidence("s 98")], seeAlso: ["hearsay"], plainAliases: ["prior bad conduct", "he has done it before"] },

  // ── Court procedure ────────────────────────────────────────────────────
  { term: "subpoena", plain: "A court order compelling someone to produce documents or turn up to give evidence.", legal: "Uniform Civil Procedure Rules 2005 (NSW) pt 33: issue requires leave in some courts, conduct money must be paid, and the recipient can object on grounds of oppression, legitimate forensic purpose or privilege. Federal courts have equivalent rules.", provisions: [ucpr("pt 33")], seeAlso: ["discovery", "client legal privilege"], plainAliases: ["court order to hand over documents", "summons to attend"] },
  { term: "discovery", plain: "Each side has to disclose the relevant documents it holds, including the unhelpful ones.", legal: "Uniform Civil Procedure Rules 2005 (NSW) pt 21: discovery is by court order rather than automatic, confined to classes of documents that are relevant to a fact in issue. Privileged documents are listed but not produced.", provisions: [ucpr("pt 21")], seeAlso: ["subpoena", "client legal privilege"], plainAliases: ["exchange documents", "disclosure"] },
  { term: "interlocutory", plain: "A step or decision along the way, before the case is finally decided.", legal: "The distinction matters for appeals: Federal Court of Australia Act 1976 (Cth) s 24(1A) requires leave to appeal from an interlocutory judgment, and state equivalents do the same. An order is interlocutory if it does not finally determine the rights in issue.", provisions: [fcaAct("s 24")], seeAlso: ["summary judgment", "ex parte"], plainAliases: ["along the way", "before the trial"] },
  { term: "ex parte", plain: "A court hearing that goes ahead without the other side present.", legal: "Allowed where urgency or the risk of tipping off would defeat the order (freezing and search orders especially), and it carries a duty of full and frank disclosure. Uniform Civil Procedure Rules 2005 (NSW) r 36.16 allows a judgment given in a party's absence to be set aside.", provisions: [ucpr("r 36.16")], seeAlso: ["interlocutory"], plainAliases: ["without the other side", "behind my back court order"] },
  { term: "pleadings", plain: "The formal documents that state each side's case — statement of claim, defence, reply.", legal: "Uniform Civil Procedure Rules 2005 (NSW) pt 14: plead material facts not evidence or law, particularise fraud and similar allegations, and expect strike-out under r 14.28 for a pleading that discloses no reasonable cause of action or is embarrassing.", provisions: [ucpr("pt 14")], seeAlso: ["summary judgment", "discovery"], plainAliases: ["statement of claim", "court documents", "defence"] },
  { term: "summary judgment", plain: "Winning (or killing) a case early because the other side has no real prospect of success.", legal: "Uniform Civil Procedure Rules 2005 (NSW) r 13.1 for judgment where there is no defence; r 13.4 and r 14.28 for dismissal and strike-out. The threshold is high — a genuinely arguable case goes to trial.", provisions: [ucpr("r 13.1"), ucpr("r 13.4")], seeAlso: ["pleadings", "interlocutory"], plainAliases: ["throw the case out", "no arguable case"] },
  { term: "security for costs", plain: "Making a plaintiff put up money to cover the defendant's costs if the claim fails.", legal: "Uniform Civil Procedure Rules 2005 (NSW) r 42.21 and Corporations Act s 1335 for corporate plaintiffs. The usual triggers are a plaintiff company that cannot pay, a plaintiff outside the jurisdiction, or a nominal plaintiff.", provisions: [ucpr("r 42.21"), corps("s 1335")], seeAlso: ["costs"], plainAliases: ["make them pay money into court"] },
  { term: "costs", plain: "Who pays the legal bills — normally the loser pays a portion of the winner's.", legal: "Civil Procedure Act 2005 (NSW) s 98 gives the court a broad discretion, exercised on the ordinary basis (reasonable costs, reasonably incurred) unless indemnity costs are justified by unreasonable conduct or a rejected offer of compromise.", provisions: [cpaNsw("s 98")], seeAlso: ["security for costs"], plainAliases: ["who pays legal fees", "loser pays"] },
  { term: "affidavit", plain: "Written evidence, sworn or affirmed, used instead of speaking from the witness box.", legal: "Uniform Civil Procedure Rules 2005 (NSW) pt 35: form, jurat, exhibits and the consequences of a defective affidavit. The maker can still be required for cross-examination.", provisions: [ucpr("pt 35")], seeAlso: ["pleadings", "subpoena"], plainAliases: ["sworn statement", "statutory declaration"] },

  // ── Public law and interpretation ──────────────────────────────────────
  { term: "judicial review", plain: "A court checking whether a government decision was made lawfully — not whether it was the best decision.", legal: "ADJR Act s 5 lists the grounds (breach of natural justice, no jurisdiction, error of law, irrelevant considerations, unreasonableness); Judiciary Act 1903 (Cth) s 39B and Constitution s 75(v) supply the constitutionally entrenched supervisory jurisdiction that no privative clause can remove.", provisions: [adjr("s 5"), judiciary("s 39B"), constitution("s 75")], seeAlso: ["jurisdictional error", "procedural fairness", "merits review"], plainAliases: ["challenge a government decision", "appeal a department decision"] },
  { term: "jurisdictional error", plain: "A mistake so fundamental that the decision-maker never had authority to decide as they did.", legal: "The doctrine, not a section: it opens the constitutionally entrenched review jurisdiction (Constitution s 75(v); Judiciary Act s 39B) and survives privative clauses. Denial of procedural fairness, misconstruing the statutory task and legal unreasonableness are the recurring categories.", provisions: [constitution("s 75")], seeAlso: ["judicial review", "procedural fairness"] },
  { term: "procedural fairness", plain: "Being told the case against you and getting a real chance to respond, before an unbiased decision-maker.", legal: "Also called natural justice. Presumed to apply to decisions affecting rights or interests unless clearly excluded; ADJR Act s 5(1)(a) makes breach a ground of review. The two limbs are the hearing rule and the bias rule.", provisions: [adjr("s 5")], seeAlso: ["judicial review", "jurisdictional error"], plainAliases: ["natural justice", "fair hearing", "not given a chance to respond"] },
  { term: "merits review", plain: "A tribunal re-deciding the case on the facts, standing in the shoes of the original decision-maker.", legal: "Different from judicial review: the tribunal can substitute the correct or preferable decision. The Administrative Review Tribunal replaced the AAT on 14 October 2024; state equivalents are NCAT, VCAT, QCAT, SACAT and SAT.", provisions: [], seeAlso: ["judicial review", "standing"], plainAliases: ["appeal to a tribunal", "get the decision looked at again"] },
  { term: "standing", plain: "Whether you are affected enough by a decision to be allowed to challenge it.", legal: "ADJR Act s 3(4) defines 'person aggrieved' as someone whose interests are adversely affected by the decision. At general law the test is a special interest beyond that of an ordinary member of the public.", provisions: [adjr("s 3")], seeAlso: ["judicial review", "merits review"], plainAliases: ["locus standi", "can I even complain"] },
  { term: "mandamus", plain: "An order compelling a public official to perform a duty they have refused or failed to perform.", legal: "One of the constitutional writs available against an officer of the Commonwealth under Constitution s 75(v) and Judiciary Act 1903 (Cth) s 39B. It compels the exercise of a duty, never a particular outcome.", provisions: [constitution("s 75"), judiciary("s 39B")], seeAlso: ["certiorari", "judicial review"], plainAliases: ["make them do their job", "force a decision"] },
  { term: "certiorari", plain: "An order quashing a decision that was made unlawfully.", legal: "Available for jurisdictional error and for error of law on the face of the record. Under the ADJR Act the statutory equivalent is an order under s 16 setting the decision aside and remitting it for reconsideration.", provisions: [adjr("s 16"), constitution("s 75")], seeAlso: ["mandamus", "judicial review"], plainAliases: ["cancel the decision", "quash the decision"] },
  { term: "habeas corpus", plain: "An urgent application testing whether someone is being held lawfully.", legal: "Preserved in the state Supreme Courts — Supreme Court Act 1970 (NSW) s 71 replaced the old writ with an order for release from custody. Federal detention is challenged through Constitution s 75(v) and Judiciary Act s 39B.", provisions: [scaNsw("s 71"), constitution("s 75")], seeAlso: ["judicial review"], plainAliases: ["unlawful detention", "held without charge"] },
  { term: "inconsistency", plain: "When a state law clashes with a Commonwealth law, the Commonwealth law wins.", legal: "Constitution s 109: the state law is inoperative to the extent of the inconsistency. Direct inconsistency (impossible to obey both) and indirect (the Commonwealth law covers the field) are the two branches.", provisions: [constitution("s 109")], seeAlso: ["corporations power"], plainAliases: ["state law vs federal law"] },
  { term: "corporations power", plain: "The Commonwealth's power to make laws about trading, financial and foreign corporations.", legal: "Constitution s 51(xx). It underpins much of the national workplace relations system and the Corporations Act referral scheme; the limits concern what may be regulated about a constitutional corporation rather than which corporations are covered.", provisions: [constitution("s 51")], seeAlso: ["inconsistency", "external affairs power"] },
  { term: "external affairs power", plain: "The Commonwealth can legislate to implement treaties it has entered.", legal: "Constitution s 51(xxix). The implementing law must be reasonably capable of being considered appropriate and adapted to the treaty obligation; it also supports laws on matters geographically external to Australia.", provisions: [constitution("s 51")], seeAlso: ["corporations power"] },
  { term: "acquisition on just terms", plain: "If the Commonwealth takes your property it must pay fairly for it.", legal: "Constitution s 51(xxxi). It requires both an acquisition (someone must obtain an identifiable proprietary benefit) and just terms; mere regulation that reduces value is generally not an acquisition. The guarantee does not bind the states.", provisions: [constitution("s 51")], seeAlso: ["inconsistency"], plainAliases: ["government took my land", "compulsory acquisition"] },
  { term: "Chapter III court", plain: "Only proper courts can exercise Commonwealth judicial power.", legal: "Constitution ch III (ss 71-80). The separation of judicial power means non-judicial bodies cannot exercise it, and a Chapter III court cannot be given functions incompatible with its judicial character — the source of the Kable principle for state courts.", provisions: [constitution("ch III"), constitution("s 71")], seeAlso: ["judicial review"], plainAliases: ["separation of powers"] },
  { term: "legislative instrument", plain: "Rules made by the executive under an Act — regulations, determinations, standards.", legal: "Legislation Act 2003 (Cth) s 8 defines it; s 15G requires registration on the Federal Register; s 42 makes it disallowable by either House; s 50 sunsets it after ten years unless action is taken.", provisions: [legAct("s 8"), legAct("s 42"), legAct("s 50")], seeAlso: ["disallowance", "sunsetting"], plainAliases: ["regulations", "delegated legislation"] },
  { term: "disallowance", plain: "Parliament can strike out a regulation without passing a new Act.", legal: "Legislation Act 2003 (Cth) s 42: either House may disallow a registered legislative instrument within the sitting-day period after tabling, and s 45 restricts remaking a substantially similar instrument for six months.", provisions: [legAct("s 42")], seeAlso: ["legislative instrument"] },
  { term: "sunsetting", plain: "Regulations expire automatically after about ten years unless remade.", legal: "Legislation Act 2003 (Cth) s 50, with the exemption and deferral machinery in pt 4 ch 3. Repeal by sunsetting is a real repeal — an instrument that has sunsetted is not merely dormant.", provisions: [legAct("s 50")], seeAlso: ["legislative instrument"] },
  { term: "purposive construction", plain: "Read a law in the way that best achieves what Parliament was trying to do.", legal: "Acts Interpretation Act 1901 (Cth) s 15AA requires the interpretation that best achieves the Act's purpose or object, and s 15AB permits recourse to extrinsic material — second reading speeches, explanatory memoranda — to confirm or resolve an ambiguous meaning.", provisions: [aia("s 15AA"), aia("s 15AB")], seeAlso: ["extrinsic material", "commencement"], plainAliases: ["what did parliament mean"] },
  { term: "extrinsic material", plain: "Explanatory memoranda and parliamentary speeches used to work out what a provision means.", legal: "Acts Interpretation Act 1901 (Cth) s 15AB lists the material and confines its use to confirming the ordinary meaning or resolving ambiguity, obscurity or an absurd result. It never displaces the text.", provisions: [aia("s 15AB")], seeAlso: ["purposive construction"], plainAliases: ["explanatory memorandum", "second reading speech"] },
  { term: "commencement", plain: "When a law actually starts to operate — often not the day it was passed.", legal: "Acts Interpretation Act 1901 (Cth) s 3A supplies the default (the 28th day after Royal Assent) where an Act is silent; commencement can also be fixed by proclamation or by a table in the Act. Legislation Act 2003 (Cth) s 12 covers legislative instruments, including the bar on retrospective operation that disadvantages a person.", provisions: [aia("s 3A"), legAct("s 12")], seeAlso: ["repeal", "legislative instrument"], plainAliases: ["when does the law start"] },
  { term: "repeal", plain: "Cancelling a law — but rights and liabilities already accrued usually survive.", legal: "Acts Interpretation Act 1901 (Cth) s 7 preserves accrued rights, liabilities and pending proceedings unless a contrary intention appears. A renamed Act is not repealed — the Trade Practices Act 1974 became the Competition and Consumer Act 2010 with the same register id.", provisions: [aia("s 7")], seeAlso: ["commencement", "sunsetting"], plainAliases: ["law cancelled", "act abolished"] },
  { term: "reckoning of time", plain: "How statutory time periods are counted, and what happens when the deadline lands on a weekend.", legal: "Acts Interpretation Act 1901 (Cth) s 36: a period expressed as running from a day excludes that day, and where the last day is a Saturday, Sunday or holiday the act may be done on the next business day. State Interpretation Acts have equivalents with their own numbering.", provisions: [aia("s 36")], seeAlso: ["limitation period"], plainAliases: ["how are days counted", "does the weekend count"] },
  { term: "person", plain: "In legislation, 'person' normally includes companies as well as human beings.", legal: "Acts Interpretation Act 1901 (Cth) s 2C: expressions used to denote persons generally include a body politic or corporate as well as an individual. State Interpretation Acts do the same.", provisions: [aia("s 2C")], seeAlso: ["separate legal entity"] },

  // ── Migration, native title, environment, supply chain ─────────────────
  { term: "character cancellation", plain: "A visa refused or cancelled because of a criminal record or conduct.", legal: "Migration Act 1958 (Cth) s 501: the character test, including the mandatory cancellation limb for a substantial criminal record while in custody, with revocation requests decided under s 501CA. Ministerial personal decisions are reviewable only by a court, not on the merits.", provisions: [migration("s 501"), migration("s 501CA")], seeAlso: ["judicial review", "merits review"], plainAliases: ["visa cancelled", "deported for a crime"] },
  { term: "protection visa", plain: "A visa for someone who cannot safely go home.", legal: "Migration Act 1958 (Cth) s 36: the Refugees Convention criterion and the complementary protection criterion (a real risk of significant harm), with the exclusion and 'safe third country' provisions in the same section.", provisions: [migration("s 36")], seeAlso: ["character cancellation"], plainAliases: ["asylum", "refugee visa"] },
  { term: "native title", plain: "Rights to land and waters that survive from traditional laws and customs.", legal: "Native Title Act 1993 (Cth) s 223 defines native title rights and interests: possessed under traditional laws and customs, a connection with the land maintained, and recognised by the common law. Extinguishment by inconsistent grants is the central battleground.", provisions: [nta("s 223")], seeAlso: ["future act"], plainAliases: ["Aboriginal land rights", "traditional owners"] },
  { term: "future act", plain: "A new grant or activity affecting land where native title may still exist.", legal: "Native Title Act 1993 (Cth) s 233 defines a future act; pt 2 div 3 sets the procedures, including the right to negotiate for mining and compulsory acquisition, and indigenous land use agreements as the negotiated alternative.", provisions: [nta("s 233")], seeAlso: ["native title"] },
  { term: "controlled action", plain: "A project that needs federal environmental approval because it will significantly affect a protected matter.", legal: "EPBC Act s 67: an action is controlled if a provision of pt 3 applies to it — world heritage, listed threatened species, migratory species, water resources for coal and gas, and the other matters of national environmental significance. Referral, assessment and approval follow in ch 4.", provisions: [epbc("s 67")], seeAlso: ["judicial review"], plainAliases: ["environmental approval", "EPBC referral"] },
  { term: "modern slavery statement", plain: "Large businesses must publish what they are doing about slavery in their supply chains.", legal: "Modern Slavery Act 2018 (Cth) s 16 sets the mandatory criteria and s 13 the reporting threshold based on consolidated revenue. The statement must be approved by the principal governing body and published on the register; the Act's compliance mechanism is transparency rather than penalty.", provisions: [slavery("s 16"), slavery("s 13")], seeAlso: ["primary duty of care"], plainAliases: ["supply chain slavery", "modern slavery reporting"] },
]
